
#include "forwardmodel.h"
#include <cmath>
// Function Definitions
//
// functionDynamicForwardTest
//     [M_nonlin,RHS_nonlin] =
//     functionDynamicForwardTest(Mw,Mc,Mp,Iwx,Iwy,Iwz,Icx,Icy,Icz,Ipx,Ipy,Ipz,Rw,Lc,Lcp,Lp,G,Tw,Tp,Q1,Q2,Q3,Q4,Q5,Q1_D,Q2_D,Q3_D,Q4_D,Q5_D)
//
// Arguments    : double Mw
//                double Mc
//                double Mp
//                double Iwx
//                double Iwy
//                double Iwz
//                double Icx
//                double Icy
//                double Icz
//                double Ipx
//                double Ipy
//                double Ipz
//                double Rw
//                double Lc
//                double Lcp
//                double Lp
//                double g
//                double Tw
//                double Tp
//                double q1
//                double q2
//                double q3
//                double q4
//                double q5
//                double q1_d
//                double q2_d
//                double q3_d
//                double q4_d
//                double q5_d
//                double M_nonlin[25]
//                double RHS_nonlin[5]
// Return Type  : void
//
void DynamicForward(double Mw, double Mc, double Mp, double Iwx,
                                double Iwy, double Iwz, double Icx, double Icy,
                                double Icz, double Ipx, double Ipy, double Ipz,
                                double Rw, double Lc, double Lcp, 
                                double g, 
                                double Tw, double Tp, 
                                double q1,
                                double q2, double q5,
                                double q1_d, double q2_d, double q3_d,
                                double q4_d, double q5_d, 
                                double M_nonlin[25],
                                double RHS_nonlin[5])
{
  double Icz_tmp;
  double Icz_tmp_tmp;
  double RHS_nonlin_tmp;
  double RHS_nonlin_tmp_tmp;
  double ab_RHS_nonlin_tmp;
  double b_Icz_tmp;
  double b_Icz_tmp_tmp;
  double b_RHS_nonlin_tmp;
  double b_RHS_nonlin_tmp_tmp;
  double bb_RHS_nonlin_tmp;
  double c_Icz_tmp;
  double c_RHS_nonlin_tmp;
  double c_RHS_nonlin_tmp_tmp;
  double cb_RHS_nonlin_tmp;
  double d_Icz_tmp;
  double d_RHS_nonlin_tmp;
  double d_RHS_nonlin_tmp_tmp;
  double db_RHS_nonlin_tmp;
  double e_Icz_tmp;
  double e_RHS_nonlin_tmp;
  double e_RHS_nonlin_tmp_tmp;
  double eb_RHS_nonlin_tmp;
  double f_Icz_tmp;
  double f_RHS_nonlin_tmp;
  double f_RHS_nonlin_tmp_tmp;
  double fb_RHS_nonlin_tmp;
  double g_Icz_tmp;
  double g_RHS_nonlin_tmp;
  double g_RHS_nonlin_tmp_tmp;
  double gb_RHS_nonlin_tmp;
  double h_Icz_tmp;
  double h_RHS_nonlin_tmp;
  double h_RHS_nonlin_tmp_tmp;
  double hb_RHS_nonlin_tmp;
  double i_Icz_tmp;
  double i_RHS_nonlin_tmp;
  double ib_RHS_nonlin_tmp;
  double j_Icz_tmp;
  double j_RHS_nonlin_tmp;
  double jb_RHS_nonlin_tmp;
  double k_Icz_tmp;
  double k_RHS_nonlin_tmp;
  double kb_RHS_nonlin_tmp;
  double l_Icz_tmp;
  double l_RHS_nonlin_tmp;
  double lb_RHS_nonlin_tmp;
  double m_RHS_nonlin_tmp;
  double mb_RHS_nonlin_tmp;
  double n_RHS_nonlin_tmp;
  double nb_RHS_nonlin_tmp;
  double o_RHS_nonlin_tmp;
  double ob_RHS_nonlin_tmp;
  double p_RHS_nonlin_tmp;
  double pb_RHS_nonlin_tmp;
  double q_RHS_nonlin_tmp;
  double r_RHS_nonlin_tmp;
  double s_RHS_nonlin_tmp;
  double t10;
  double t14;
  double t15;
  double t16;
  double t17;
  double t18;
  double t19;
  double t2;
  double t20;
  double t21;
  double t22;
  double t23;
  double t25;
  double t27;
  double t27_tmp;
  double t28;
  double t29;
  double t3;
  double t30;
  double t31;
  double t32;
  double t33;
  double t34;
  double t34_tmp;
  double t34_tmp_tmp;
  double t35;
  double t35_tmp;
  double t35_tmp_tmp;
  double t36;
  double t36_tmp;
  double t36_tmp_tmp;
  double t37;
  double t37_tmp;
  double t38;
  double t39;
  double t4;
  double t40;
  double t41;
  double t42;
  double t43;
  double t44;
  double t45;
  double t46;
  double t5;
  double t50;
  double t51;
  double t52;
  double t54;
  double t55;
  double t57;
  double t57_tmp;
  double t58;
  double t58_tmp;
  double t59;
  double t59_tmp;
  double t6;
  double t60;
  double t60_tmp;
  double t60_tmp_tmp;
  double t61;
  double t61_tmp;
  double t67;
  double t67_tmp;
  double t67_tmp_tmp;
  double t68;
  double t69;
  double t7;
  double t8;
  double t_RHS_nonlin_tmp;
  double u_RHS_nonlin_tmp;
  double v_RHS_nonlin_tmp;
  double w_RHS_nonlin_tmp;
  double x_RHS_nonlin_tmp;
  double y_RHS_nonlin_tmp;
  //     This function was generated by the Symbolic Math Toolbox version 9.2.
  //     27-Nov-2023 11:20:34
  t2 = std::cos(q1);
  t3 = std::cos(q2);
  t4 = std::cos(q5);
  t5 = std::sin(q1);
  t6 = std::sin(q2);
  t7 = std::sin(q5);
  t8 = Lc * Lc;
  t10 = Rw * Rw;
  t14 = q1_d * q1_d;
  t15 = q2_d * q2_d;
  t16 = q3_d * q3_d;
  t27_tmp = Lc * Lcp * Mp;
  t27 = t27_tmp * 2.0;
  t17 = t2 * t2;
  t18 = t3 * t3;
  t19 = t4 * t4;
  t20 = std::sin(q1 * 2.0);
  t21 = std::sin(q2 * 2.0);
  t22 = std::sin(q5 * 2.0);
  t23 = Ipx * t3;
  t25 = Ipz * t5;
  t28 = Mc * t8;
  t29 = Mp * t8;
  t30 = Mp * (Lcp * Lcp);
  t31 = Mc * t10;
  t32 = Mp * t10;
  t33 = Mw * t10;
  t34_tmp_tmp = Lc * Mc;
  t34_tmp = t34_tmp_tmp * Rw;
  t34 = t34_tmp * t3;
  t35_tmp_tmp = Lc * Mp;
  t35_tmp = t35_tmp_tmp * Rw;
  t35 = t35_tmp * t3;
  t36_tmp_tmp = Lcp * Mp;
  t36_tmp = t36_tmp_tmp * Rw;
  t36 = t36_tmp * t3;
  t37_tmp = Ipx * t2;
  t37 = t37_tmp * t6;
  t43 = t5 * t27;
  t57_tmp = t34_tmp * t6;
  t57 = t57_tmp * t16;
  t58_tmp = t35_tmp * t6;
  t58 = t58_tmp * t16;
  t59_tmp = t36_tmp * t6;
  t59 = t59_tmp * t16;
  t60_tmp_tmp = Ipy * t2;
  t60_tmp = t60_tmp_tmp * t3;
  t60 = t60_tmp * t4 * t7;
  t61_tmp = Ipz * t2;
  t61 = t61_tmp * t3 * t4 * t7;
  t38 = Ipy * t19;
  t39 = Ipz * t19;
  t40 = t34 * 2.0;
  t41 = t35 * 2.0;
  t42 = t36 * 2.0;
  t44 = t5 * t28;
  t45 = t5 * t29;
  t46 = t5 * t30;
  t50 = t5 * t34;
  t51 = t5 * t35;
  t52 = t5 * t36;
  t55 = t19 * t25;
  t67_tmp_tmp = q1_d * q3_d;
  t67_tmp = t67_tmp_tmp * t2;
  t67 = t67_tmp * t34 * -2.0;
  t68 = t67_tmp * t35 * -2.0;
  t69 = t67_tmp * t36 * -2.0;
  t8 = (t34 + t35) + t36;
  t54 = t5 * t38;
  t10 = (((((Iwy * t5 + t5 * t31) + t5 * t32) + t5 * t33) + t50) + t51) + t52;
  t19 = (((((((((((Icy * t5 + t25) + t43) + t44) + t45) + t46) + t50) + t51) +
            t52) +
           t54) +
          t60) -
         t55) -
        t61;
  M_nonlin[0] =
      (((((((((((((((((((Icz + Ipy) + Iwx) + t31) + t32) + t33) - t38) + t39) +
                  t40) +
                 t41) +
                t42) +
               Icx * t18) -
              Icz * t18) +
             Ipx * t18) -
            Ipy * t18) +
           t18 * t27) +
          t18 * t28) +
         t18 * t29) +
        t18 * t30) +
       t18 * t38) +
      t18 * -t39;
  Icz_tmp = t4 * t6 * t7;
  M_nonlin[1] = Icz_tmp * (Ipy - Ipz);
  b_Icz_tmp = t2 * t3;
  c_Icz_tmp = Ipy * t4;
  Icz_tmp_tmp = Icx * t2;
  d_Icz_tmp = Icz_tmp_tmp * t3;
  b_Icz_tmp_tmp = Icz * t2;
  e_Icz_tmp = b_Icz_tmp_tmp * t3;
  f_Icz_tmp = t34_tmp * t2;
  g_Icz_tmp = t35_tmp * t2;
  h_Icz_tmp = t36_tmp * t2;
  i_Icz_tmp = c_Icz_tmp * t5;
  M_nonlin[2] =
      -t6 * ((((((((((((((t2 * t23 + d_Icz_tmp) - e_Icz_tmp) - t60_tmp) +
                       b_Icz_tmp * t27) +
                      b_Icz_tmp * t28) +
                     b_Icz_tmp * t29) +
                    b_Icz_tmp * t30) +
                   t4 * t7 * t25) +
                  b_Icz_tmp * t38) +
                 b_Icz_tmp * -t39) -
                i_Icz_tmp * t7) +
               f_Icz_tmp) +
              g_Icz_tmp) +
             h_Icz_tmp);
  M_nonlin[3] = 0.0;
  M_nonlin[4] = t23;
  j_Icz_tmp = Ipz * t4;
  M_nonlin[5] = c_Icz_tmp * t6 * t7 - j_Icz_tmp * t6 * t7;
  k_Icz_tmp = Icy + Ipz;
  M_nonlin[6] = (((((k_Icz_tmp + t27) + t28) + t29) + t30) + t38) - t39;
  M_nonlin[7] = t19;
  M_nonlin[8] = t8;
  M_nonlin[9] = 0.0;
  l_Icz_tmp = b_Icz_tmp * t6;
  M_nonlin[10] =
      (((((((((((((-t2 * t6 * t23 - d_Icz_tmp * t6) + e_Icz_tmp * t6) +
                 t60_tmp * t6) -
                l_Icz_tmp * t28) -
               l_Icz_tmp * t29) -
              l_Icz_tmp * t30) -
             Icz_tmp * t25) -
            l_Icz_tmp * t38) +
           l_Icz_tmp * t39) -
          f_Icz_tmp * t6) -
         g_Icz_tmp * t6) -
        h_Icz_tmp * t6) +
       i_Icz_tmp * t6 * t7) -
      t27_tmp * t2 * t3 * t6 * 2.0;
  M_nonlin[11] = t19;
  Icz_tmp = Icx * t17;
  d_Icz_tmp = Ipx * t17;
  e_Icz_tmp = t17 * t18;
  M_nonlin[12] =
      ((((((((((((((((((((((((((((((((((((((k_Icz_tmp + Iwy) + t27) + t28) +
                                         t29) +
                                        t30) +
                                       t31) +
                                      t32) +
                                     t33) +
                                    t38) +
                                   t40) +
                                  t41) +
                                 t42) -
                                t39) +
                               Icz_tmp) -
                              Icy * t17) +
                             d_Icz_tmp) -
                            Ipz * t17) -
                           Iwy * t17) +
                          Iwz * t17) -
                         t17 * t31) -
                        t17 * t32) -
                       t17 * t33) -
                      t17 * t34 * 2.0) -
                     t17 * t35 * 2.0) -
                    t17 * t36 * 2.0) -
                   t17 * t38) +
                  t17 * t39) +
                 t5 * t60 * 2.0) -
                Icz_tmp * t18) +
               Icz * t17 * t18) -
              d_Icz_tmp * t18) +
             Ipy * t17 * t18) -
            e_Icz_tmp * t28) -
           e_Icz_tmp * t29) -
          e_Icz_tmp * t30) -
         e_Icz_tmp * t38) +
        e_Icz_tmp * t39) -
       t27_tmp * t17 * t18 * 2.0) -
      b_Icz_tmp * t4 * t7 * t25 * 2.0;
  M_nonlin[13] = t10;
  M_nonlin[14] = -t37;
  M_nonlin[15] = 0.0;
  M_nonlin[16] = t8;
  M_nonlin[17] = t10;
  M_nonlin[18] = ((Iwy + t31) + t32) + t33;
  M_nonlin[19] = 0.0;
  M_nonlin[20] = t23;
  M_nonlin[21] = 0.0;
  M_nonlin[22] = -t37;
  M_nonlin[23] = 0.0;
  M_nonlin[24] = Ipx;
  RHS_nonlin_tmp = t16 * t20;
  b_RHS_nonlin_tmp = t2 * t16;
  c_RHS_nonlin_tmp = q3_d * q4_d * t2;
  RHS_nonlin_tmp_tmp = q2_d * q3_d;
  d_RHS_nonlin_tmp = RHS_nonlin_tmp_tmp * t2;
  b_RHS_nonlin_tmp_tmp = q1_d * q2_d;
  e_RHS_nonlin_tmp = b_RHS_nonlin_tmp_tmp * t21;
  c_RHS_nonlin_tmp_tmp = q2_d * q5_d;
  f_RHS_nonlin_tmp = c_RHS_nonlin_tmp_tmp * t6;
  d_RHS_nonlin_tmp_tmp = q3_d * q5_d;
  g_RHS_nonlin_tmp = d_RHS_nonlin_tmp_tmp * t6;
  h_RHS_nonlin_tmp = t2 * t5 * t16;
  i_RHS_nonlin_tmp = b_RHS_nonlin_tmp * t18;
  j_RHS_nonlin_tmp = Ipx * q2_d;
  k_RHS_nonlin_tmp = Ipy * q2_d;
  l_RHS_nonlin_tmp = Ipy * q1_d;
  m_RHS_nonlin_tmp = Ipz * q2_d;
  e_RHS_nonlin_tmp_tmp = Icx * q2_d * q3_d;
  n_RHS_nonlin_tmp = e_RHS_nonlin_tmp_tmp * t2;
  f_RHS_nonlin_tmp_tmp = Icz * q2_d * q3_d;
  o_RHS_nonlin_tmp = f_RHS_nonlin_tmp_tmp * t2;
  p_RHS_nonlin_tmp = j_RHS_nonlin_tmp * q3_d * t2;
  g_RHS_nonlin_tmp_tmp = k_RHS_nonlin_tmp * q3_d;
  q_RHS_nonlin_tmp = g_RHS_nonlin_tmp_tmp * t2;
  h_RHS_nonlin_tmp_tmp = Ipy * t3;
  r_RHS_nonlin_tmp = h_RHS_nonlin_tmp_tmp * t4 * t7;
  s_RHS_nonlin_tmp = Ipz * t3 * t4 * t7;
  t_RHS_nonlin_tmp = b_RHS_nonlin_tmp_tmp * t3 * t6;
  u_RHS_nonlin_tmp = d_RHS_nonlin_tmp * t18;
  v_RHS_nonlin_tmp = l_RHS_nonlin_tmp * q5_d;
  t8 = Ipz * q1_d;
  w_RHS_nonlin_tmp = t8 * q5_d;
  x_RHS_nonlin_tmp = r_RHS_nonlin_tmp * t16;
  y_RHS_nonlin_tmp = s_RHS_nonlin_tmp * t16;
  ab_RHS_nonlin_tmp = Icx * q1_d;
  bb_RHS_nonlin_tmp = Icz * q1_d;
  cb_RHS_nonlin_tmp = Ipx * q1_d;
  k_RHS_nonlin_tmp *= q5_d;
  db_RHS_nonlin_tmp = m_RHS_nonlin_tmp * q5_d;
  eb_RHS_nonlin_tmp = t34_tmp_tmp * g;
  fb_RHS_nonlin_tmp = t35_tmp_tmp * g;
  gb_RHS_nonlin_tmp = t36_tmp_tmp * g;
  hb_RHS_nonlin_tmp = Ipy * q3_d * q5_d;
  ib_RHS_nonlin_tmp = ab_RHS_nonlin_tmp * q2_d;
  jb_RHS_nonlin_tmp = bb_RHS_nonlin_tmp * q2_d;
  kb_RHS_nonlin_tmp = l_RHS_nonlin_tmp * q2_d;
  lb_RHS_nonlin_tmp = cb_RHS_nonlin_tmp * q2_d;
  mb_RHS_nonlin_tmp = RHS_nonlin_tmp_tmp * t3;
  nb_RHS_nonlin_tmp = g_RHS_nonlin_tmp_tmp * t3;
  ob_RHS_nonlin_tmp = t27_tmp * q2_d * q3_d;
  pb_RHS_nonlin_tmp = Ipz * t16;
  m_RHS_nonlin_tmp = m_RHS_nonlin_tmp * q3_d * t2;
  RHS_nonlin[0] =
      ((((((((((((((((((((((((((((((((((Icx * t16 * t20 * -0.5 +
                                        Icy * t16 * t20 / 2.0) -
                                       Ipx * t16 * t20 / 2.0) +
                                      pb_RHS_nonlin_tmp * t20 / 2.0) +
                                     Iwy * t16 * t20 / 2.0) -
                                    Iwz * t16 * t20 / 2.0) +
                                   RHS_nonlin_tmp * t31 / 2.0) +
                                  RHS_nonlin_tmp * t32 / 2.0) +
                                 RHS_nonlin_tmp * t33 / 2.0) +
                                b_RHS_nonlin_tmp * t54) +
                               b_RHS_nonlin_tmp * -t55) -
                              g_RHS_nonlin_tmp * t25) +
                             c_RHS_nonlin_tmp * t31) +
                            c_RHS_nonlin_tmp * t32) +
                           c_RHS_nonlin_tmp * t33) +
                          c_RHS_nonlin_tmp * t34) +
                         c_RHS_nonlin_tmp * t35) +
                        c_RHS_nonlin_tmp * t36) +
                       d_RHS_nonlin_tmp * t40) +
                      d_RHS_nonlin_tmp * t41) +
                     d_RHS_nonlin_tmp * t42) +
                    e_RHS_nonlin_tmp * t27) -
                   f_RHS_nonlin_tmp * t38 * 2.0) +
                  e_RHS_nonlin_tmp * t28) +
                 f_RHS_nonlin_tmp * t39 * 2.0) +
                e_RHS_nonlin_tmp * t29) +
               e_RHS_nonlin_tmp * t30) -
              g_RHS_nonlin_tmp * t54 * 2.0) +
             g_RHS_nonlin_tmp * t55 * 2.0) -
            g_RHS_nonlin_tmp * t60 * 2.0) +
           g_RHS_nonlin_tmp * t61 * 2.0) +
          h_RHS_nonlin_tmp * t40) +
         h_RHS_nonlin_tmp * t41) +
        h_RHS_nonlin_tmp * t42) +
       (((((((((((((((((((((((((((((((((i_RHS_nonlin_tmp * t43 +
                                        i_RHS_nonlin_tmp * t44) +
                                       i_RHS_nonlin_tmp * t45) +
                                      i_RHS_nonlin_tmp * t46) +
                                     i_RHS_nonlin_tmp * t54) +
                                    i_RHS_nonlin_tmp * -t55) +
                                   Mc * Rw * g * t5) +
                                  Mp * Rw * g * t5) +
                                 Mw * Rw * g * t5) -
                                n_RHS_nonlin_tmp) +
                               ib_RHS_nonlin_tmp * t21) +
                              Icy * q2_d * q3_d * t2) +
                             o_RHS_nonlin_tmp) -
                            jb_RHS_nonlin_tmp * t21) -
                           p_RHS_nonlin_tmp) +
                          j_RHS_nonlin_tmp * q5_d * t6) +
                         lb_RHS_nonlin_tmp * t21) +
                        q_RHS_nonlin_tmp) +
                       k_RHS_nonlin_tmp * t6) -
                      kb_RHS_nonlin_tmp * t21) -
                     v_RHS_nonlin_tmp * t22) +
                    m_RHS_nonlin_tmp) -
                   db_RHS_nonlin_tmp * t6) +
                  w_RHS_nonlin_tmp * t22) +
                 Iwy * q3_d * q4_d * t2) +
                eb_RHS_nonlin_tmp * t3 * t5) +
               fb_RHS_nonlin_tmp * t3 * t5) +
              gb_RHS_nonlin_tmp * t3 * t5) +
             n_RHS_nonlin_tmp * t18 * 2.0) -
            o_RHS_nonlin_tmp * t18 * 2.0) +
           Ipx * q3_d * q5_d * t5 * t6) +
          p_RHS_nonlin_tmp * t18 * 2.0) +
         hb_RHS_nonlin_tmp * t5 * t6) -
        q_RHS_nonlin_tmp * t18 * 2.0)) +
      ((((((((((((((((((((((((Icz_tmp_tmp * t5 * t16 * t18 -
                              b_Icz_tmp_tmp * t5 * t16 * t18) +
                             t37_tmp * t5 * t16 * t18) -
                            r_RHS_nonlin_tmp * t15) -
                           x_RHS_nonlin_tmp) -
                          t60_tmp_tmp * t5 * t16 * t18) +
                         s_RHS_nonlin_tmp * t15) +
                        y_RHS_nonlin_tmp) +
                       t_RHS_nonlin_tmp * t38 * 2.0) -
                      t_RHS_nonlin_tmp * t39 * 2.0) +
                     u_RHS_nonlin_tmp * t28 * 2.0) +
                    u_RHS_nonlin_tmp * t29 * 2.0) +
                   u_RHS_nonlin_tmp * t30 * 2.0) +
                  u_RHS_nonlin_tmp * t38 * 2.0) -
                 u_RHS_nonlin_tmp * t39 * 2.0) +
                mb_RHS_nonlin_tmp * t4 * t7 * t25 * 2.0) +
               t34_tmp * q1_d * q2_d * t6 * 2.0) +
              t35_tmp * q1_d * q2_d * t6 * 2.0) +
             t36_tmp * q1_d * q2_d * t6 * 2.0) +
            v_RHS_nonlin_tmp * t4 * t7 * t18 * 2.0) -
           w_RHS_nonlin_tmp * t4 * t7 * t18 * 2.0) +
          x_RHS_nonlin_tmp * t17 * 2.0) -
         y_RHS_nonlin_tmp * t17 * 2.0) +
        ob_RHS_nonlin_tmp * t2 * t18 * 4.0) -
       nb_RHS_nonlin_tmp * t4 * t5 * t7 * 2.0);
  RHS_nonlin_tmp = t14 * t21;
  b_RHS_nonlin_tmp = q1_d * q5_d * t6;
  t36_tmp_tmp = t3 * t6;
  c_RHS_nonlin_tmp = t36_tmp_tmp * t14;
  Icz_tmp_tmp = ab_RHS_nonlin_tmp * q3_d;
  e_RHS_nonlin_tmp = Icz_tmp_tmp * t2;
  f_RHS_nonlin_tmp = bb_RHS_nonlin_tmp * q3_d * t2;
  b_Icz_tmp_tmp = cb_RHS_nonlin_tmp * q3_d;
  g_RHS_nonlin_tmp = b_Icz_tmp_tmp * t2;
  t34 = l_RHS_nonlin_tmp * q3_d;
  h_RHS_nonlin_tmp = t34 * t2;
  i_RHS_nonlin_tmp = d_RHS_nonlin_tmp_tmp * t2;
  j_RHS_nonlin_tmp = i_RHS_nonlin_tmp * t3;
  l_RHS_nonlin_tmp = t67_tmp * t18;
  n_RHS_nonlin_tmp = t36_tmp_tmp * t16 * t17;
  o_RHS_nonlin_tmp = Icy * q1_d;
  p_RHS_nonlin_tmp = o_RHS_nonlin_tmp * q3_d;
  r_RHS_nonlin_tmp = t8 * q3_d;
  s_RHS_nonlin_tmp = Ipz * q3_d * q5_d;
  t_RHS_nonlin_tmp = cb_RHS_nonlin_tmp * q5_d;
  u_RHS_nonlin_tmp = Icx * t3;
  x_RHS_nonlin_tmp = Icz * t3;
  y_RHS_nonlin_tmp = t27_tmp * q1_d;
  ab_RHS_nonlin_tmp = t34_tmp * q3_d * q4_d;
  bb_RHS_nonlin_tmp = t35_tmp * q3_d * q4_d;
  cb_RHS_nonlin_tmp = t36_tmp * q3_d * q4_d;
  t35 = t34 * t3 * t4;
  t36 = hb_RHS_nonlin_tmp * t2 * t3;
  t37_tmp = hb_RHS_nonlin_tmp * t4;
  t37 = t60_tmp_tmp * t4;
  t34_tmp_tmp = y_RHS_nonlin_tmp * q3_d * t2;
  t35_tmp_tmp = Ipy * t14;
  RHS_nonlin[1] =
      (((((((((((((((((((((((((((((((((((-Tw - t57) - t58) - t59) + t67) +
                                     t68) +
                                    t69) +
                                   t17 * t57) +
                                  t17 * t58) +
                                 t17 * t59) -
                                Icx * t14 * t21 / 2.0) +
                               Icz * t14 * t21 / 2.0) -
                              Ipx * t14 * t21 / 2.0) +
                             t35_tmp_tmp * t21 / 2.0) -
                            RHS_nonlin_tmp * t28 / 2.0) -
                           RHS_nonlin_tmp * t29 / 2.0) -
                          RHS_nonlin_tmp * t30 / 2.0) -
                         i_RHS_nonlin_tmp * t23) -
                        b_RHS_nonlin_tmp * t38 * 2.0) +
                       b_RHS_nonlin_tmp * t39 * 2.0) -
                      c_RHS_nonlin_tmp * t38) +
                     c_RHS_nonlin_tmp * t39) +
                    t6 * t16 * t17 * t23) +
                   e_RHS_nonlin_tmp) -
                  p_RHS_nonlin_tmp * t2) -
                 f_RHS_nonlin_tmp) +
                g_RHS_nonlin_tmp) -
               t_RHS_nonlin_tmp * t6) -
              h_RHS_nonlin_tmp) +
             v_RHS_nonlin_tmp * t6) +
            k_RHS_nonlin_tmp * t22) -
           r_RHS_nonlin_tmp * t2) -
          w_RHS_nonlin_tmp * t6) -
         db_RHS_nonlin_tmp * t22) -
        t27_tmp * t14 * t21) +
       (((((((((((((((((((((((((((-Lc * Mc * Rw * t6 * t14 - t58_tmp * t14) -
                                 t59_tmp * t14) +
                                eb_RHS_nonlin_tmp * t2 * t6) +
                               fb_RHS_nonlin_tmp * t2 * t6) +
                              gb_RHS_nonlin_tmp * t2 * t6) -
                             e_RHS_nonlin_tmp * t18 * 2.0) +
                            f_RHS_nonlin_tmp * t18 * 2.0) -
                           g_RHS_nonlin_tmp * t18 * 2.0) +
                          t36) +
                         h_RHS_nonlin_tmp * t18 * 2.0) -
                        s_RHS_nonlin_tmp * t2 * t3) +
                       u_RHS_nonlin_tmp * t6 * t16 * t17) -
                      x_RHS_nonlin_tmp * t6 * t16 * t17) -
                     h_RHS_nonlin_tmp_tmp * t6 * t16 * t17) -
                    d_RHS_nonlin_tmp_tmp * t4 * t7 * t25 * 2.0) -
                   j_RHS_nonlin_tmp * t38 * 2.0) -
                  l_RHS_nonlin_tmp * t28 * 2.0) +
                 j_RHS_nonlin_tmp * t39 * 2.0) -
                l_RHS_nonlin_tmp * t29 * 2.0) -
               l_RHS_nonlin_tmp * t30 * 2.0) -
              l_RHS_nonlin_tmp * t38 * 2.0) +
             l_RHS_nonlin_tmp * t39 * 2.0) +
            n_RHS_nonlin_tmp * t27) +
           n_RHS_nonlin_tmp * t28) +
          n_RHS_nonlin_tmp * t29) +
         n_RHS_nonlin_tmp * t30) +
        n_RHS_nonlin_tmp * t38)) +
      (((((((((n_RHS_nonlin_tmp * -t39 -
               t67_tmp_tmp * t3 * t4 * t7 * t25 * 2.0) +
              t2 * t4 * t6 * t7 * t16 * t25) +
             t37_tmp * t5 * t7 * 2.0) -
            t34_tmp_tmp * t18 * 4.0) -
           ab_RHS_nonlin_tmp * t5 * t6) -
          bb_RHS_nonlin_tmp * t5 * t6) -
         cb_RHS_nonlin_tmp * t5 * t6) +
        t35 * t5 * t7 * 2.0) -
       t37 * t5 * t6 * t7 * t16);
  RHS_nonlin_tmp = b_RHS_nonlin_tmp_tmp * t2;
  i_RHS_nonlin_tmp = t67_tmp_tmp * t20;
  n_RHS_nonlin_tmp = Iwy * q1_d;
  w_RHS_nonlin_tmp = ib_RHS_nonlin_tmp * t2;
  eb_RHS_nonlin_tmp = jb_RHS_nonlin_tmp * t2;
  fb_RHS_nonlin_tmp = kb_RHS_nonlin_tmp * t2;
  gb_RHS_nonlin_tmp = c_RHS_nonlin_tmp_tmp * t2;
  ib_RHS_nonlin_tmp = gb_RHS_nonlin_tmp * t3;
  jb_RHS_nonlin_tmp = RHS_nonlin_tmp * t18;
  mb_RHS_nonlin_tmp = mb_RHS_nonlin_tmp * t6 * t17;
  i_Icz_tmp = t34_tmp * t5 * t6;
  k_Icz_tmp = t35_tmp * t5 * t6;
  l_Icz_tmp = t36_tmp * t5 * t6;
  t37 = t37 * t6 * t7;
  h_Icz_tmp = t61_tmp * t4 * t6 * t7;
  y_RHS_nonlin_tmp = y_RHS_nonlin_tmp * q2_d * t2;
  d_RHS_nonlin_tmp_tmp = t34_tmp * q2_d * q3_d;
  g_Icz_tmp = d_RHS_nonlin_tmp_tmp * t6;
  t36_tmp_tmp = t35_tmp * q2_d * q3_d;
  f_Icz_tmp = t36_tmp_tmp * t6;
  t10 = t36_tmp * q2_d * q3_d;
  t19 = t10 * t6;
  t35 *= t7;
  t37_tmp = t37_tmp * t7 * t17;
  Icz_tmp = r_RHS_nonlin_tmp * t3 * t4 * t7;
  d_Icz_tmp = s_RHS_nonlin_tmp * t4 * t7 * t17;
  e_Icz_tmp = n_RHS_nonlin_tmp * q3_d;
  t8 *= q2_d;
  RHS_nonlin[2] =
      ((((((((((((((((((((((((((((((((gb_RHS_nonlin_tmp * t23 -
                                      RHS_nonlin_tmp * t28 * 2.0) -
                                     RHS_nonlin_tmp * t29 * 2.0) -
                                    RHS_nonlin_tmp * t30 * 2.0) -
                                   b_RHS_nonlin_tmp * t25) -
                                  RHS_nonlin_tmp * t38 * 2.0) +
                                 RHS_nonlin_tmp * t39 * 2.0) -
                                i_RHS_nonlin_tmp * t31) -
                               t67_tmp * t50 * 4.0) -
                              i_RHS_nonlin_tmp * t32) -
                             t67_tmp * t51 * 4.0) -
                            i_RHS_nonlin_tmp * t33) -
                           t67_tmp * t52 * 4.0) -
                          t67_tmp * t54 * 2.0) +
                         t67_tmp * t55 * 2.0) -
                        b_RHS_nonlin_tmp * t54 * 2.0) +
                       b_RHS_nonlin_tmp * t55 * 2.0) -
                      b_RHS_nonlin_tmp * t60 * 2.0) +
                     b_RHS_nonlin_tmp * t61 * 2.0) -
                    t5 * t6 * t14 * t23) -
                   c_RHS_nonlin_tmp * t44) -
                  c_RHS_nonlin_tmp * t45) -
                 c_RHS_nonlin_tmp * t46) -
                c_RHS_nonlin_tmp * t54) +
               c_RHS_nonlin_tmp * t55) -
              w_RHS_nonlin_tmp) +
             Icz_tmp_tmp * t20) -
            o_RHS_nonlin_tmp * q2_d * t2) -
           p_RHS_nonlin_tmp * t20) +
          eb_RHS_nonlin_tmp) +
         ((((((((((((((((((((((((((((-Ipx * q1_d * q2_d * t2 +
                                     b_Icz_tmp_tmp * t20) +
                                    fb_RHS_nonlin_tmp) +
                                   hb_RHS_nonlin_tmp * t22) -
                                  t8 * t2) -
                                 r_RHS_nonlin_tmp * t20) -
                                s_RHS_nonlin_tmp * t22) -
                               n_RHS_nonlin_tmp * q4_d * t2) -
                              e_Icz_tmp * t20) +
                             Iwz * q1_d * q3_d * t20) +
                            w_RHS_nonlin_tmp * t18 * 2.0) -
                           eb_RHS_nonlin_tmp * t18 * 2.0) -
                          t_RHS_nonlin_tmp * t5 * t6) +
                         lb_RHS_nonlin_tmp * t2 * t18 * 2.0) +
                        k_RHS_nonlin_tmp * t2 * t3) +
                       v_RHS_nonlin_tmp * t5 * t6) -
                      fb_RHS_nonlin_tmp * t18 * 2.0) -
                     db_RHS_nonlin_tmp * t2 * t3) -
                    u_RHS_nonlin_tmp * t5 * t6 * t14) +
                   x_RHS_nonlin_tmp * t5 * t6 * t14) +
                  h_RHS_nonlin_tmp_tmp * t5 * t6 * t14) -
                 j_RHS_nonlin_tmp * t25 * 2.0) -
                c_RHS_nonlin_tmp_tmp * t4 * t7 * t25 * 2.0) -
               ib_RHS_nonlin_tmp * t38 * 2.0) +
              jb_RHS_nonlin_tmp * t28 * 2.0) -
             RHS_nonlin_tmp_tmp * t6 * t17 * t23 * 2.0) +
            ib_RHS_nonlin_tmp * t39 * 2.0) +
           jb_RHS_nonlin_tmp * t29 * 2.0) +
          jb_RHS_nonlin_tmp * t30 * 2.0)) +
        (((((((((((((((((((((((jb_RHS_nonlin_tmp * t38 * 2.0 -
                               jb_RHS_nonlin_tmp * t39 * 2.0) -
                              j_RHS_nonlin_tmp * t54 * 4.0) -
                             l_RHS_nonlin_tmp * t44 * 2.0) +
                            j_RHS_nonlin_tmp * t55 * 4.0) -
                           l_RHS_nonlin_tmp * t45 * 2.0) -
                          l_RHS_nonlin_tmp * t46 * 2.0) -
                         l_RHS_nonlin_tmp * t54 * 2.0) +
                        l_RHS_nonlin_tmp * t55 * 2.0) -
                       mb_RHS_nonlin_tmp * t28 * 2.0) -
                      mb_RHS_nonlin_tmp * t29 * 2.0) -
                     mb_RHS_nonlin_tmp * t30 * 2.0) -
                    mb_RHS_nonlin_tmp * t38 * 2.0) +
                   mb_RHS_nonlin_tmp * t39 * 2.0) -
                  y_RHS_nonlin_tmp * 4.0) +
                 g_Icz_tmp * 2.0) -
                ab_RHS_nonlin_tmp * t6) +
               f_Icz_tmp * 2.0) -
              bb_RHS_nonlin_tmp * t6) +
             t19 * 2.0) -
            cb_RHS_nonlin_tmp * t6) -
           i_Icz_tmp * t14) +
          i_Icz_tmp * t15) -
         k_Icz_tmp * t14)) +
       ((((((((((((((((((((((k_Icz_tmp * t15 - l_Icz_tmp * t14) +
                            l_Icz_tmp * t15) -
                           e_RHS_nonlin_tmp * t5 * t18 * 2.0) -
                          e_RHS_nonlin_tmp_tmp * t3 * t6 * t17 * 2.0) +
                         f_RHS_nonlin_tmp * t5 * t18 * 2.0) +
                        f_RHS_nonlin_tmp_tmp * t3 * t6 * t17 * 2.0) -
                       g_RHS_nonlin_tmp * t5 * t18 * 2.0) +
                      t35 * 2.0) +
                     t36 * t5 * 2.0) +
                    k_RHS_nonlin_tmp * t4 * t5 * t7 * 2.0) +
                   h_RHS_nonlin_tmp * t5 * t18 * 2.0) +
                  nb_RHS_nonlin_tmp * t6 * t17 * 2.0) -
                 t37_tmp * 2.0) -
                Icz_tmp * 2.0) +
               d_Icz_tmp * 2.0) -
              t37 * t14) +
             t37 * t15) +
            h_Icz_tmp * t14) -
           h_Icz_tmp * t15) +
          y_RHS_nonlin_tmp * t18 * 4.0) -
         t27_tmp * t3 * t5 * t6 * t14 * 2.0) -
        g_Icz_tmp * t17 * 2.0)) +
      (((((((((f_Icz_tmp * t17 * -2.0 - t19 * t17 * 2.0) - t35 * t17 * 4.0) -
             t37_tmp * t18 * 2.0) +
            Icz_tmp * t17 * 4.0) +
           d_Icz_tmp * t18 * 2.0) -
          d_RHS_nonlin_tmp * t4 * t6 * t7 * t25 * 2.0) -
         t34_tmp_tmp * t5 * t18 * 4.0) -
        ob_RHS_nonlin_tmp * t3 * t6 * t17 * 4.0) +
       q_RHS_nonlin_tmp * t4 * t5 * t6 * t7 * 2.0);
  RHS_nonlin[3] = (((((((((((((((Tw + t57) + t58) + t59) + t67) + t68) + t69) -
                           t67_tmp * t31 * 2.0) -
                          t67_tmp * t32 * 2.0) -
                         t67_tmp * t33 * 2.0) -
                        e_Icz_tmp * t2) +
                       t57_tmp * t15) +
                      t58_tmp * t15) +
                     t59_tmp * t15) +
                    d_RHS_nonlin_tmp_tmp * t5 * t6 * 2.0) +
                   t36_tmp_tmp * t5 * t6 * 2.0) +
                  t10 * t5 * t6 * 2.0;
  RHS_nonlin_tmp = b_RHS_nonlin_tmp_tmp * t6;
  b_RHS_nonlin_tmp = t67_tmp_tmp * t6;
  c_RHS_nonlin_tmp = b_Icz_tmp * t16;
  e_RHS_nonlin_tmp = c_Icz_tmp * t7;
  f_RHS_nonlin_tmp = j_Icz_tmp * t7;
  g_RHS_nonlin_tmp = d_RHS_nonlin_tmp * t3;
  h_RHS_nonlin_tmp = e_RHS_nonlin_tmp * t16 * t17;
  i_RHS_nonlin_tmp = f_RHS_nonlin_tmp * t16 * t17;
  RHS_nonlin[4] = (((((((((((((((((((((((((((((Tp + t35_tmp_tmp * t22 / 2.0) -
                                              Ipy * t15 * t22 / 2.0) -
                                             Ipy * t16 * t22 / 2.0) -
                                            Ipz * t14 * t22 / 2.0) +
                                           Ipz * t15 * t22 / 2.0) +
                                          pb_RHS_nonlin_tmp * t22 / 2.0) +
                                         d_RHS_nonlin_tmp * t23) +
                                        b_RHS_nonlin_tmp * t25) +
                                       RHS_nonlin_tmp * t38 * 2.0) -
                                      RHS_nonlin_tmp * t39 * 2.0) +
                                     b_RHS_nonlin_tmp * t54 * 2.0) -
                                    b_RHS_nonlin_tmp * t55 * 2.0) +
                                   b_RHS_nonlin_tmp * t60 * 2.0) -
                                  b_RHS_nonlin_tmp * t61 * 2.0) +
                                 c_RHS_nonlin_tmp * t25) +
                                c_RHS_nonlin_tmp * t54 * 2.0) -
                               c_RHS_nonlin_tmp * t55 * 2.0) +
                              lb_RHS_nonlin_tmp * t6) -
                             kb_RHS_nonlin_tmp * t6) +
                            t8 * t6) -
                           b_Icz_tmp_tmp * t5 * t6) -
                          q_RHS_nonlin_tmp * t3) -
                         t34 * t5 * t6) +
                        m_RHS_nonlin_tmp * t3) -
                       t60_tmp * t5 * t16) -
                      e_RHS_nonlin_tmp * t14 * t18) +
                     h_RHS_nonlin_tmp) +
                    f_RHS_nonlin_tmp * t14 * t18) -
                   i_RHS_nonlin_tmp) +
                  (((((RHS_nonlin_tmp_tmp * t4 * t7 * t25 * 2.0 +
                       g_RHS_nonlin_tmp * t38 * 2.0) -
                      g_RHS_nonlin_tmp * t39 * 2.0) -
                     g_RHS_nonlin_tmp_tmp * t4 * t5 * t7 * 2.0) +
                    h_RHS_nonlin_tmp * t18) -
                   i_RHS_nonlin_tmp * t18);
}

